### ISSUE TITLE
Fills

### ISSUE THREAD

**Issue by flyguyee** [mdunnio/coinbase-pro#1]
Does this provide a way of getting the list of fills for a user, and if so, can all fills be obtained at once, or just for a specific cryptocurrency?

**Comment by mdunnio** [comment]
Short answer, no. I only have the unauthenticated websocket feed (as well as some unauthenticated requests) implemented at this time.

According to their documentation (https://docs.pro.coinbase.com/#list-fills), you should be able to get a list of "recent" fills per product id.

**Comment by flyguyee** [comment]
Thank you for the prompt response. Are you having a difficult time coding the authenticated client in Haskell?

**Comment by mdunnio** [comment]
Nah, I'm just not working on it right now. If I get some more free time I might flesh out the feature set a bit more, but I can't promise anything soon. I'm accepting PRs. :)

**Comment by mdunnio** [comment]
A fills call has been added since the latest release 0.2.0. Please check the README.
