### ISSUE TITLE
Cut a release?

### ISSUE THREAD

**Issue by colonelpanic8** [mdunnio/coinbase-pro#21]
The bumps to cryptonite that were made are needed for compatibility with both stackage and nixpkgs package sets. Any chance you could cut a release? Alternatively you could even just upload a modified cabal file, and keep the versions as they are.

**Comment by colonelpanic8** [comment]
@mdunnio ping? Should be really easy to upload a modified cabal file

**Comment by mdunnio** [comment]
Yeah, I can do this. Hopefully I can get it done by tomorrow.

**Comment by mdunnio** [comment]
https://hackage.haskell.org/package/coinbase-pro-0.9.2.2

Thanks for your patience!

**Comment by colonelpanic8** [comment]
Awesome! Thanks @mdunnio
